ema:
  full_name: 樱羽艾玛
  emotion_count: 11
  offset: [-50,200]
  scale: 0.65
  font: font3.ttf
  "平静": [3]
  "喜悦": [3,8]
  "喜爱": [6,11,10]
  "惊讶": [9]
  "困惑": [7]
  "无语": [4,7]
  "悲伤": [2,6,10,11]
  "愤怒": [1,4]
  "恐惧": [2,5]
hiro:
  full_name: 二阶堂希罗
  emotion_count: 16
  offset: [-150,180]
  scale: 0.85
  font: font3.ttf
  "平静": [5,6]
  "喜悦": [5,6,13,14]
  "喜爱": [9,10]
  "惊讶": [15,16]
  "困惑": [11,12,15,16]
  "无语": [7,13,14]
  "悲伤": [3,4,11,12]
  "愤怒": [1,2]
  "恐惧": [7,8]
CreatureHiro:
  full_name: 二阶堂希罗（魔女化）
  emotion_count: 25
  offset: [-100,180]
  offsetX:
    "6": -130
    "9": -140
    "10": 90
    "11": 90
    "16": 90
    "20": 90
    "21": 90
  scale: 0.68
  font: font3.ttf
  "平静": [1,2,3,5,8,9,10,11]
  "喜悦": [3,5,8,10,11,25]
  "喜爱": [25]
  "惊讶": [1,15,23,24]
  "困惑": [1,15,17,23]
  "无语": [1,2,4,15,16,23,24,25]
  "悲伤": [9]
  "愤怒": [4,7,14,17,20,22,23,24]
  "恐惧": [12,13,15]
sherry:
  full_name: 橘雪莉
  emotion_count: 8
  offset: [-100,210]
  scale: 0.7
  font: font3.ttf
  "平静": [3,6]
  "喜悦": [3,7]
  "喜爱": [5,7]
  "惊讶": [8]
  "困惑": [6]
  "无语": [1,6]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4]
hanna:
  full_name: 远野汉娜
  emotion_count: 8
  offset: [-100,150]
  scale: 0.6
  font: font3.ttf
  "平静": [3,7]
  "喜悦": [3,7]
  "喜爱": [3,5,6]
  "惊讶": [8]
  "困惑": [3]
  "无语": [3,6]
  "悲伤": [2,5]
  "愤怒": [1,3]
  "恐惧": [4,6]
anan:
  full_name: 夏目安安
  emotion_count: 12
  offset: [-160,250]
  scale: 0.7
  font: font3.ttf
  "平静": [7]
  "喜悦": [5,7,9,11]
  "喜爱": [5,9,11]
  "惊讶": [3,8]
  "困惑": [3,6,10]
  "无语": [1,3,7,10,12]
  "悲伤": [2,3,6]
  "愤怒": [1,4]
  "恐惧": [1,6,10,12]
yuki:
  full_name: 月代雪
  emotion_count: 20
  offset: [-180,200]
  offsetY:
    "12": -150
  scale: 0.6
  font: font3.ttf
  "平静": [2,3,4,5]
  "喜悦": [2,3,4,5,6,7,8,18,19]
  "喜爱": [8,18,19]
  "惊讶": [9,13,15,16,17]
  "困惑": [9,13,15,20]
  "无语": [1,4,5,10,11,14,16,17,19,20]
  "悲伤": [17]
  "愤怒": [1,7,13,16,17]
  "恐惧": [16,17]
meruru:
  full_name: 冰上梅露露
  emotion_count: 16
  offset: [-100,250]
  scale: 0.75
  font: font3.ttf
  "平静": [13,14]
  "喜悦": [13,14]
  "喜爱": [8,9,13,14]
  "惊讶": [15,16]
  "困惑": [15,16]
  "无语": [1,8,9,13]
  "悲伤": [3,4,5,10,11,12]
  "愤怒": [1,2]
  "恐惧": [6,7]
noa:
  full_name: 城崎诺亚
  emotion_count: 8
  offset: [-140,200]
  scale: 0.68
  font: font3.ttf
  "平静": [3]
  "喜悦": [3,7]
  "喜爱": [1,5,7]
  "惊讶": [8]
  "困惑": [3,6]
  "无语": [1,3,6,7]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4,6]
reia:
  full_name: 莲见蕾雅
  emotion_count: 8
  offset: [-120,200]
  scale: 0.83
  font: font3.ttf
  "平静": [3,7]
  "喜悦": [7]
  "喜爱": [5,7]
  "惊讶": [8]
  "困惑": [3,6,8]
  "无语": [1,3]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4]
miria:
  full_name: 佐伯米莉亚
  emotion_count: 8
  offset: [-190,200]
  scale: 0.71
  font: font3.ttf
  "平静": [7]
  "喜悦": [7]
  "喜爱": [5,7]
  "惊讶": [3,8]
  "困惑": [6]
  "无语": [1,6,7]
  "悲伤": [2,6]
  "愤怒": [1,]
  "恐惧": [4,8]
nanoka:
  full_name: 黑部奈叶香
  emotion_count: 8
  offset: [-140,200]
  scale: 0.84
  font: font3.ttf
  "平静": [3,7]
  "喜悦": [3,7]
  "喜爱": [5,7]
  "惊讶": [3,8]
  "困惑": [3,6]
  "无语": [1]
  "悲伤": [2,6]
  "愤怒": [1]
  "恐惧": [4]
mago:
  full_name: 宝生玛格
  emotion_count: 8
  offset: [-100,200]
  scale: 0.68
  font: font3.ttf
  "平静": [3]
  "喜悦": [3,5,7]
  "喜爱": [5,7]
  "惊讶": [8]
  "困惑": [6]
  "无语": [1,3,6]
  "悲伤": [2]
  "愤怒": [1]
  "恐惧": [4]
alisa:
  full_name: 紫藤亚里沙
  emotion_count: 8
  offset: [-100,190]
  scale: 0.72
  font: font3.ttf
  "平静": [3,6,7]
  "喜悦": [7]
  "喜爱": [7]
  "惊讶": [5,8]
  "困惑": [3]
  "无语": [1,5,6,7]
  "悲伤": [2]
  "愤怒": [1]
  "恐惧": [2,4]
coco:
  full_name: 泽渡可可    
  emotion_count: 8
  offset: [-120,190]
  scale: 0.72
  font: font3.ttf
  "平静": [3]
  "喜悦": [3,7]
  "喜爱": [5]
  "惊讶": [8]
  "困惑": [6]
  "无语": [6]
  "悲伤": [2]
  "愤怒": [1]
  "恐惧": [4]
# 在下方添加新角色信息，依次为全名、表情差分数量、使用字体
# 如：
#   warden:
#     full_name: 典狱长
#     emotion_count: 表情数量
#     offset: 立绘偏移值
#     scale: 立绘缩放
#     font: font3.ttf
#     "平静": 
#     "喜悦": 
#     "喜爱": 
#     "惊讶": 
#     "困惑": 
#     "无语": 
#     "悲伤": 
#     "愤怒": 
#     "恐惧": 